### ISSUE TITLE
Edition 2021: add Thomas More & Open Recogntion Logo as partners for Edubadges project 

### ISSUE THREAD

**Issue by jeborsel** [opensummerofcode/website#152]
Missing partner logo's here: https://osoc.be/editions/2021/belbadges

**Comment by jbelien** [comment]
No worries, could you upload the logos here ?

**Comment by jeborsel** [comment]
[Open Recogntion](https://gblobscdn.gitbook.com/assets%2F-Mbef5VGwnuL5Dcf_gDG%2F-McxTIQNLOUDERtSnQc0%2F-McxV1fNrHgpWjhkUUHy%2Fopenrecognitionalliance-logo.svg?alt=media&token=5a8afdc5-dee3-49aa-b323-8de77121af7f)

&

[Thomas More](https://gblobscdn.gitbook.com/assets%2F-Mbef5VGwnuL5Dcf_gDG%2F-MdzxpuxHgE43pElr7Jr%2F-MdzxwFI0Okxnl4U6Cyr%2Flogo-thomasmore.svg?alt=media&token=7c83107d-35fd-47d2-bc10-b345f6d52f3f)

They are also missing on the front: https://osoc.be/partners
