### ISSUE TITLE
add logo of FOD Economie to project page

### ISSUE THREAD

**Issue by jeborsel** [opensummerofcode/website#256]
Could you add the logo of the FOD Economie here: https://osoc.be/editions/2022/inspector-widget  , thanks!
![logo-en](https://user-images.githubusercontent.com/9434649/180962169-f7db3193-f164-4f35-9f7c-a2855626a3d8.svg)

**Comment by jbelien** [comment]
Done in 64db32f3f191dc79dcdaa9dd066db46886aa687d
