### ISSUE TITLE
add logo of Dalberg Data Insights to project page

### ISSUE THREAD

**Issue by jeborsel** [opensummerofcode/website#257]
Coudl you add the logo of Dalberg Data Insights here as partner: https://osoc.be/editions/2022/vac-voice-assistant-confidentiality , thanks ! 
![Subbrands_DalbergDataInsights_RGB_Red](https://user-images.githubusercontent.com/9434649/180962496-97556081-2761-4d4e-97a2-554d9e371d64.jpg)

**Comment by jbelien** [comment]
No worries!
Could you upload here the logo in SVG ? Thanks!

**Comment by jeborsel** [comment]
![DalbergDataInsights](https://user-images.githubusercontent.com/9434649/181020283-790d1a3b-ba7f-4fa4-8f6c-7e49aabf167e.svg)

**Comment by jbelien** [comment]
Done in 86fa3b5119eba3ccfea523447152f7cc8e8098b1
