### ISSUE TITLE
Correct names

### ISSUE THREAD

**Issue by mietcls** [opensummerofcode/website#260]
Remove "Stijn" from Cat Catry's name
Change "Beatrice Postelnicu" to "Ava Blanche"

They both changed or are in the process of changing their names.

I couldn't find out where to do it myself...

![image](https://user-images.githubusercontent.com/1572885/181623786-ccbafb83-78a6-4d0b-806e-fc50c00b876f.png)

![image](https://user-images.githubusercontent.com/1572885/181623830-4c54572e-2a6e-4a1f-8345-7aade5c11360.png)

**Comment by jbelien** [comment]
Dear @beatricepostelnicu @Denperidge, my deepest apologies!
I blindly copy pasted all the names from the application forms...

This is now fixed (see 23e55bcb97b4d7cfedc7b93a95043a6d0e760e6c)!

**Comment by mietcls** [comment]
@jbelien osoc is hectic and you did your utter best we know! Thanks for the quick reaction and we did not see it either in the hectic flow.

**Comment by Denperidge** [comment]
Hi! Honestly no problem, I know it wasn’t malintent and indeed just from a
copypaste/automation from the data source
Thank you so much for the quick reaction and fix! <3
